In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_parquet(r'D:\Learning\FPT_polytechnic\Sem6\datn_outlier_hs_nlmt\data\mlmart_base\v2_preprocessing.parquet')
df.head(10)

,gen_id,site_id,geo_id,date_id,time_id,timestamp,is_dst_repeat,full_date,year,month,...,cloud_cover_low,cloud_cover_mid,cloud_cover_high,wind_speed,precipitation_mm,sunshine_duration,weather_code,weather_type_is_day,weather_condition,weather_description
0,1,1,1,20200101,15,2020-01-01 00:15:00,0,2020-01-01,2020,1,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
1,11,1,1,20200101,30,2020-01-01 00:30:00,0,2020-01-01,2020,1,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
2,21,1,1,20200101,45,2020-01-01 00:45:00,0,2020-01-01,2020,1,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
3,31,1,1,20200101,100,2020-01-01 01:00:00,0,2020-01-01,2020,1,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
4,41,1,1,20200101,115,2020-01-01 01:15:00,0,2020-01-01,2020,1,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
5,51,1,1,20200101,130,2020-01-01 01:30:00,0,2020-01-01,2020,1,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
6,61,1,1,20200101,145,2020-01-01 01:45:00,0,2020-01-01,2020,1,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
7,71,1,1,20200101,200,2020-01-01 02:00:00,0,2020-01-01,2020,1,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
8,81,1,1,20200101,215,2020-01-01 02:15:00,0,2020-01-01,2020,1,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
9,91,1,1,20200101,230,2020-01-01 02:30:00,0,2020-01-01,2020,1,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>

In [3]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 2731946 entries, 0 to 2731945
Data columns (total 47 columns):
 #   Column                    Dtype
---  ------                    -----
 0   gen_id                    Int64
 1   site_id                   Int64
 2   geo_id                    Int64
 3   date_id                   Int64
 4   time_id                   Int64
 5   timestamp                 datetime64[us]
 6   is_dst_repeat             Int64
 7   full_date                 datetime64[ms]
 8   year                      Int64
 9   month                     Int64
 10  day                       Int64
 11  day_of_week               Int64
 12  hour                      Int64
 13  minute                    Int64
 14  energy_generated_kwh      float64
 15  gmm_if_outlier_flag       boolean
 16  gmm_if_outlier_reason     str
 17  campus_name               string
 18  capacity_kw               float64
 19  number_of_panels          float64
 20  panel                     string
 21  inverter                  string
 22  optimizers                string
 23  site_metric               string
 24  location_name             string
 25  latitude                  float64
 26  longitude                 float64
 27  weather_id                Int64
 28  weather_type_id           Int64
 29  weather_timestamp         datetime64[us]
 30  weather_join_method       str
 31  weather_is_day            Int64
 32  shortwave_radiation       float64
 33  direct_normal_irradiance  float64
 34  diffuse_solar_radiation   float64
 35  temperature_c             float64
 36  cloud_cover_total         float64
 37  cloud_cover_low           float64
 38  cloud_cover_mid           float64
 39  cloud_cover_high          float64
 40  wind_speed                float64
 41  precipitation_mm          float64
 42  sunshine_duration         float64
 43  weather_code              Int64
 44  weather_type_is_day       Int64
 45  weather_condition         string
 46  weather_description       string
dtypes: Int64(17), boolean(1), datetime64[ms](1), datetime64[us](2), float64(16), str(2), string(8)
memory usage: 1.4 GB

,gen_id,site_id,geo_id,date_id,time_id,timestamp,is_dst_repeat,full_date,year,month,...,temperature_c,cloud_cover_total,cloud_cover_low,cloud_cover_mid,cloud_cover_high,wind_speed,precipitation_mm,sunshine_duration,weather_code,weather_type_is_day
count,2731946.0,2731946.0,2731946.0,2731946.0,2731946.0,2731946,2731946.0,2731946,2731946.0,2731946.0,...,2.731758e+06,2.731758e+06,2.731758e+06,2.731758e+06,2.731758e+06,2.731758e+06,2.731758e+06,2.731758e+06,2731758.0,2731758.0
mean,1365973.5,21.694635,21.694635,20209220.312697,1169.917795,2021-05-05 00:27:30.469225,0.0,2021-05-04 12:36:33.407000,2020.857289,6.317637,...,1.479317e+01,5.632270e+01,2.723020e+01,2.473750e+01,2.970294e+01,1.169396e+01,9.835868e-02,1.384095e+03,9.792462,0.511677
min,1.0,1.0,1.0,20200101.0,0.0,2020-01-01 00:15:00,0.0,2020-01-01 00:00:00,2020.0,1.0,...,-4.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0
25%,682987.25,11.0,11.0,20201114.0,545.0,2020-11-14 17:30:00,0.0,2020-11-14 00:00:00,2020.0,3.0,...,1.020000e+01,1.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,7.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0
50%,1365973.5,22.0,22.0,20210516.0,1145.0,2021-05-16 02:30:00,0.0,2021-05-16 00:00:00,2021.0,6.0,...,1.390000e+01,6.300000e+01,5.000000e+00,3.000000e+00,0.000000e+00,1.090000e+01,0.000000e+00,0.000000e+00,2.0,1.0
75%,2048959.75,33.0,33.0,20211104.0,1745.0,2021-11-04 07:30:00,0.0,2021-11-04 00:00:00,2021.0,9.0,...,1.850000e+01,9.900000e+01,4.700000e+01,4.200000e+01,7.400000e+01,1.550000e+01,0.000000e+00,3.600000e+03,3.0,1.0
max,2731946.0,42.0,42.0,20220423.0,2345.0,2022-04-23 23:45:00,0.0,2022-04-23 00:00:00,2022.0,12.0,...,4.420000e+01,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,4.930000e+01,2.530000e+01,3.600000e+03,73.0,1.0
std,788645.023593,12.309507,12.309507,6586.432366,692.258103,NaN,0.0,NaN,0.675197,3.56173,...,6.216702e+00,4.014712e+01,3.664506e+01,3.409795e+01,4.079076e+01,6.076881e+00,4.939792e-01,1.695456e+03,18.964388,0.499864

In [5]:
drop_null_capa = df['capacity_kw'].dropna()
drop_null_capa.describe()

count    1.599868e+06
mean     9.532623e+01
std      1.233715e+02
min      2.139000e+01
25%      3.927000e+01
50%      5.115000e+01
75%      7.722000e+01
max      5.398000e+02
Name: capacity_kw, dtype: float64